[repository]
name = "sc-eprocessos"
changelog = "CHANGELOG.md"
version = "version.txt"
version_format = "semver"
container_images_prefix = "ghcr.io/simplesconsultoria/sc-eprocessos"
compose = ["docker-compose.yml"]

[repository.towncrier]
section = "Project"
settings = "towncrier.toml"

[backend.package]
name = "sc.eprocessos"
path = "backend"
changelog = "backend/CHANGELOG.md"
code_path = "src/sc/eprocessos"
towncrier_settings = "backend/pyproject.toml"
base_package = "Products.CMFPlone"
publish = true

[frontend.package]
name = "@simplesconsultoria/volto-eprocessos"
path = "frontend/packages/volto-eprocessos"
changelog = "frontend/packages/volto-eprocessos/CHANGELOG.md"
code_path = "src"
towncrier_settings = "frontend/packages/volto-eprocessos/towncrier.toml"
base_package = "@plone/volto"
publish = true

[cookieplone]
template = "monorepo_addon"
template_version = "0f1e1aa8c8da289805aa7ae184e67e04412abc00"
generated_date = "2026-04-02 17:13:00"
